version: "3.8"
services:
  dev-mysql:
    platform: linux/arm64/v8
    image: library/mysql:8.0.33
    container_name: "auction-mysql"
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auction
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
